name: Rebuild codegen

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches:
      - main


jobs:
  check:
    outputs:
      latest_commit: ${{ steps.fetch.outputs.LATEST_COMMIT }}
      previous_commit: ${{ steps.fetch.outputs.PREVIOUS_COMMIT }}
      has_new_commits: ${{ steps.fetch.outputs.HAS_NEW_COMMITS }}
    runs-on: ubuntu-latest
    name: Check for new commits
    steps:
      - name: Check for new commits
        id: fetch
        run: |
          # Get latest geode-sdk/bindings commit and store it to a ENV variable
          git clone https://github.com/geode-sdk/bindings.git
          cd bindings
          export LATEST_COMMIT=$(git rev-parse HEAD)
          cd ..

          # Get latest release tag
          export LATEST_RELEASE=$(curl -s https://api.github.com/repos/prevter/bindings-meta/releases/latest | jq -r '.tag_name')

          # Compare the latest commit with the latest release tag
          export LATEST_COMMIT=$(echo $LATEST_COMMIT | cut -c1-7)
          export LATEST_RELEASE=$(echo $LATEST_RELEASE | cut -c1-7)
          if [ "$LATEST_COMMIT" == "$LATEST_RELEASE" ]; then
            echo "No new commits since last release"
            echo "HAS_NEW_COMMITS=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Export the latest commit to be used in the next step
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_OUTPUT
          echo "PREVIOUS_COMMIT=$LATEST_RELEASE" >> $GITHUB_OUTPUT
          echo "HAS_NEW_COMMITS=true" >> $GITHUB_OUTPUT

  generate:
    strategy:
      matrix:
        config:
          - { platform: Win32, version: "2.204" }
          - { platform: MacOS, version: "2.200" }
          - { platform: Win64, version: "2.206" }
          - { platform: MacOS, version: "2.206" }
          - { platform: iOS, version: "2.206" }
          
    needs: check
    if: needs.check.outputs.has_new_commits == 'true'
    runs-on: ubuntu-latest
    name: Run codegen
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S . -DGEODE_TARGET_PLATFORM=${{ matrix.config.platform }} -DGEODE_GD_VERSION=${{ matrix.config.version }}
      
      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.platform }}-${{ matrix.config.version }}
          path: ./output

  publish:
    needs: ['generate', 'check']
    runs-on: ubuntu-latest
    name: Publish results
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          path: codegen
          merge-multiple: true
  
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export LATEST_COMMIT=${{ needs.check.outputs.latest_commit }}
          export PREVIOUS_COMMIT=${{ needs.check.outputs.previous_commit }}
          gh release create $LATEST_COMMIT -t "Bindings commit $LATEST_COMMIT" -n "Codegen output for https://github.com/geode-sdk/bindings/compare/$PREVIOUS_COMMIT...$LATEST_COMMIT" codegen/*
  
      - name: Build website
        run: |
          cp codegen/* website/public/.
          cd website
          npm install
          npm run build
          cd ..

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
